image: $CI_REGISTRY/ict/images/alpine/base:latest

stages:
  - build_and_test

build_and_test:
  stage: build_and_test
  script:
    - |
      # Only one topmost folder is expected per commit; git hook on my machine makes sure that's true
      TOPMOST_FOLDER=$(git diff --name-only "$CI_COMMIT_BEFORE_SHA" "$CI_COMMIT_SHA" | awk -F/ '{print $1}' | sort -u | head -n 1)

      cd "$TOPMOST_FOLDER"

      WARNINGS=$(gcc -Wall -pedantic -o output *.c 2>&1)

      if [ -n "$WARNINGS" ]; then
        echo "Graceless build"
        echo "$WARNINGS"
        exit 1
      fi

      TESTFILES=("tests"/*)
      
      for FILE in "${TESTFILES[@]}"; do
        FILENAME=$(basename "$FILE")
      
        # Split type_id into type and id
        IFS='_' read -r TYPE ID <<< "$FILENAME"
      
        if [ "$TYPE" == "output" ]; then
          continue
        fi
      
        OUTPUT_FILE="tests/output_$ID"
      
        # Check if the output file exists
        if [ ! -f "$OUTPUT_FILE" ]; then
          echo "Warning: Output file for $FILENAME not found. The heck?"
          continue
        fi

        TEST_RES=$(./output < $FILENAME > tmp && diff tmp OUTPUT_FILE)
        if [ -z "$TEST_RES" ]; then
            echo Test $ID passsed
        else
            echo "Test $ID failed"
            cat tmp
            rm tmp
            exit 1
        fi
      done

      rm tmp